[package]
name = "belchi"
version = "1.0.0"
edition = "2025"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "multipart", "blocking"] }
serde_json = "1.0"
walkdir = "2.3"
once_cell = "1.18.0"
dirs = "6.0.0"
